CREATE DATABASE IF NOT EXISTS xzunun_gestor_evidencias;
USE xzunun_gestor_evidencias;
CREATE TABLE IF NOT EXISTS tabla_administradores(
    `clave` VARCHAR(255) NOT NULL PRIMARY KEY,
    `nombres` VARCHAR(255) NOT NULL,
    `apellido_paterno` VARCHAR(255) NOT NULL,
    `apellido_materno` VARCHAR(255) NOT NULL,
    `fecha_nacimiento` DATE NOT NULL,
    `sexo` VARCHAR(255) NOT NULL,
    `email_institucional` VARCHAR(255) NOT NULL,
    `contrasenia` TEXT NOT NULL,
    `foto_perfil` VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS tabla_materias(
    `clave` VARCHAR(255) NOT NULL PRIMARY KEY,
    `nombre` VARCHAR(255) NOT NULL,
    `semestre` INT NOT NULL,
    `unidades` INT NOT NULL,
    `carrera` VARCHAR(255) NOT NULL
) ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS tabla_alumnos(
    `numero_control` VARCHAR(255) NOT NULL PRIMARY KEY,
    `carrera` VARCHAR(255) NOT NULL,
    `nombres` VARCHAR(255) NOT NULL,
    `apellido_paterno` VARCHAR(255) NOT NULL,
    `apellido_materno` VARCHAR(255) NOT NULL,
    `fecha_nacimiento` DATE NOT NULL,
    `sexo` VARCHAR(255) NOT NULL,
    `email_institucional` VARCHAR(255) NOT NULL,
    `contrasenia` TEXT NOT NULL,
    `foto_perfil` VARCHAR(255) NOT NULL
) ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS tabla_profesores(
    `clave` VARCHAR(255) NOT NULL PRIMARY KEY,
    `nombres` VARCHAR(255) NOT NULL,
    `apellido_paterno` VARCHAR(255) NOT NULL,
    `apellido_materno` VARCHAR(255) NOT NULL,
    `fecha_nacimiento` DATE NOT NULL,
    `sexo` VARCHAR(255) NOT NULL,
    `email_institucional` VARCHAR(255) NOT NULL,
    `contrasenia` TEXT NOT NULL,
    `foto_perfil` VARCHAR(255) NOT NULL
) ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS tabla_materias_profesores(
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `clave_profesor` VARCHAR(255) NOT NULL,
    `clave_materia` VARCHAR(255) NOT NULL,
    `grupo` VARCHAR(255) NOT NULL,
    `ciclo` VARCHAR(255) NOT NULL
) ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS tabla_alumnos_profesores(
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `numero_control_alumno` VARCHAR(255) NOT NULL,
    `clave_profesor` VARCHAR(255) NOT NULL,
    `semestre_materia` INT NOT NULL,
    `grupo_profesor` VARCHAR(255) NOT NULL,
    `ciclo_profesor` VARCHAR(255) NOT NULL
) ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS tabla_archivos(
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `numero_control_alumno` VARCHAR(255) NOT NULL,
    `nombre` VARCHAR(255) NOT NULL,
    `extension` VARCHAR(255) NOT NULL,
    `nombre_materia` VARCHAR(255) NOT NULL,
    `unidad_materia` INT NOT NULL,
    `semestre_materia` INT NOT NULL,
    `ciclo_profesor` VARCHAR(255) NOT NULL,
    `fecha_insercion` DATE DEFAULT CURDATE(),
    `hora_insercion` TIME DEFAULT CURTIME(),
    `ruta` VARCHAR(255) NOT NULL
) ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS tabla_ciclos(
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `ciclo` VARCHAR(255) NOT NULL,
    `estado` BOOL NOT NULL
) ENGINE = InnoDB;
ALTER TABLE tabla_materias_profesores ADD FOREIGN KEY (`clave_profesor`) REFERENCES tabla_profesores(`clave`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tabla_materias_profesores ADD FOREIGN KEY (`clave_materia`) REFERENCES tabla_materias(`clave`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tabla_alumnos_profesores ADD FOREIGN KEY (`numero_control_alumno`) REFERENCES tabla_alumnos(`numero_control`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tabla_alumnos_profesores ADD FOREIGN KEY (`clave_profesor`) REFERENCES tabla_profesores(`clave`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tabla_archivos ADD FOREIGN KEY (`numero_control_alumno`) REFERENCES tabla_alumnos(`numero_control`) ON DELETE CASCADE ON UPDATE CASCADE;
INSERT INTO tabla_materias(`clave`, `nombre`, `semestre`, `unidades`, `carrera`) VALUES
    ("cdisc1", "cálculo diferencial", 1, 5, "ingeniería en sistemas computacionales"),
    ("fpisc1", "fundamentos de programación", 1, 5, "ingeniería en sistemas computacionales"),
    ("teisc1", "taller de ética", 1, 5, "ingeniería en sistemas computacionales"),
    ("mdisc1", "matemáticas discretas", 1, 5, "ingeniería en sistemas computacionales"),
    ("taisc1", "taller de administración", 1, 5, "ingeniería en sistemas computacionales"),
    ("fiisc1", "fundamentos de investigación", 1, 5, "ingeniería en sistemas computacionales"),
    ("ciisc2", "cálculo integral", 2, 5, "ingeniería en sistemas computacionales"),
    ("pooisc2", "programación orientada a objetos", 2, 5, "ingeniería en sistemas computacionales"),
    ("cfisc2", "contabilidad financiera", 2, 5, "ingeniería en sistemas computacionales"),
    ("qisc2", "química", 2, 5, "ingeniería en sistemas computacionales"),
    ("alisc2", "álgebra lineal", 2, 5, "ingeniería en sistemas computacionales"),
    ("peisc2", "probabilidad y estadística", 2, 5, "ingeniería en sistemas computacionales"),
    ("cvisc3", "cálculo vectorial", 3, 5, "ingeniería en sistemas computacionales"),
    ("edisc3", "estructura de datos", 3, 5, "ingeniería en sistemas computacionales"),
    ("ceisc3", "cultura empresarial", 3, 5, "ingeniería en sistemas computacionales"),
    ("ioisc3", "investigación de operaciones", 3, 5, "ingeniería en sistemas computacionales"),
    ("dsisc3", "desarrollo sustentable", 3, 5, "ingeniería en sistemas computacionales"),
    ("fgisc3", "física general", 3, 5, "ingeniería en sistemas computacionales"),
    ("edisc4", "ecuaciones diferenciales", 4, 5, "ingeniería en sistemas computacionales"),
    ("mnisc4", "métodos numéricos", 4, 5, "ingeniería en sistemas computacionales"),
    ("tapisc4", "tópicos avanzados de programación", 4, 5, "ingeniería en sistemas computacionales"),
    ("fbdisc4", "fundamentos de base de datos", 4, 5, "ingeniería en sistemas computacionales"),
    ("sisc4", "simulación", 4, 5, "ingeniería en sistemas computacionales"),
    ("peadisc4", "principios eléctricos y aplicaciones digitales", 4, 5, "ingeniería en sistemas computacionales"),
    ("gisc5", "graficación", 5, 5, "ingeniería en sistemas computacionales"),
    ("ftisc5", "fundamentos de telecomunicaciones", 5, 5, "ingeniería en sistemas computacionales"),
    ("soisc5", "sistemas operativos", 5, 5, "ingeniería en sistemas computacionales"),
    ("tbdisc5", "taller de base de datos", 5, 5, "ingeniería en sistemas computacionales"),
    ("fisisc5", "fundamentos de ingeniería de software", 5, 5, "ingeniería en sistemas computacionales"),
    ("acisc5", "arquitectura de computadoras", 5, 5, "ingeniería en sistemas computacionales"),
    ("la1isc6", "lenguajes y autómatas 1", 6, 5, "ingeniería en sistemas computacionales"),
    ("rcisc6", "redes de computadoras", 6, 5, "ingeniería en sistemas computacionales"),
    ("tsoisc6", "taller de sistemas operativos", 6, 5, "ingeniería en sistemas computacionales"),
    ("abdisc6", "administración de base de datos", 6, 5, "ingeniería en sistemas computacionales"),
    ("isisc6", "ingeniería de software", 6, 5, "ingeniería en sistemas computacionales"),
    ("liisc6", "lenguajes de interfaz", 6, 5, "ingeniería en sistemas computacionales"),
    ("li2isc7", "lenguajes y autómatas 2", 7, 5, "ingeniería en sistemas computacionales"),
    ("cerdisc7", "conmutación y enrutamiento en redes de datos", 7, 5, "ingeniería en sistemas computacionales"),
    ("ti1isc7", "taller de investigación 1", 7, 5, "ingeniería en sistemas computacionales"),
    ("gpsisc7", "gestión de proyectos de software", 7, 5, "ingeniería en sistemas computacionales"),
    ("spisc7", "sistemas programables", 7, 5, "ingeniería en sistemas computacionales"),
    ("plfisc8", "programación lógica y funcional", 8, 5, "ingeniería en sistemas computacionales"),
    ("arisc8", "administración de redes", 8, 5, "ingeniería en sistemas computacionales"),
    ("ti2isc8", "taller de investigación 2", 8, 5, "ingeniería en sistemas computacionales"),
    ("pwisc8", "programación web", 8, 5, "ingeniería en sistemas computacionales"),
    ("iaisc9", "inteligencia artificial", 9, 5, "ingeniería en sistemas computacionales");
INSERT INTO tabla_materias(`clave`, `nombre`, `semestre`, `unidades`, `carrera`) VALUES
    ("fiige1", "fundamentos de investigación", 1, 5, "ingeniería en gestión empresarial"),
    ("cdige1", "cálculo diferencial", 1, 5, "ingeniería en gestión empresarial"),
    ("dhige1", "desarrollo humano", 1, 5, "ingeniería en gestión empresarial"),
    ("fgeige1", "fundamentos de gestión empresarial", 1, 5, "ingeniería en gestión empresarial"),
    ("ffige1", "fundamentos de física", 1, 5, "ingeniería en gestión empresarial"),
    ("fqige1", "fundamentos de química", 1, 5, "ingeniería en gestión empresarial"),
    ("ciige2", "cálculo integral", 2, 5, "ingeniería en gestión empresarial"),
    ("saeige2", "software de aplicación ejecutivo", 2, 5, "ingeniería en gestión empresarial"),
    ("conige2", "contabilidad orientada a los negocios", 2, 5, "ingeniería en gestión empresarial"),
    ("dsige2", "dinámica social", 2, 5, "ingeniería en gestión empresarial"),
    ("teige2", "taller de ética", 2, 5, "ingeniería en gestión empresarial"),
    ("llige2", "legislación laboral", 2, 5, "ingeniería en gestión empresarial"),
    ("mloige3", "marco legal de las organizaciones", 3, 5, "ingeniería en gestión empresarial"),
    ("pedige3", "probabilidad y estadística descriptiva", 3, 5, "ingeniería en gestión empresarial"),
    ("ceige3", "costos empresariales", 3, 5, "ingeniería en gestión empresarial"),
    ("hd1ige3", "habilidades directivas 1", 3, 5, "ingeniería en gestión empresarial"),
    ("eeige3", "economía empresarial", 3, 5, "ingeniería en gestión empresarial"),
    ("alige3", "álgebra lineal", 3, 5, "ingeniería en gestión empresarial"),
    ("ieige4", "ingeniería ecónomica", 4, 5, "ingeniería en gestión empresarial"),
    ("ei1ige4", "estadística inferencial 1", 4, 5, "ingeniería en gestión empresarial"),
    ("ipeige4", "instrumentos de presupuestación empresarial", 4, 5, "ingeniería en gestión empresarial"),
    ("hd2ige4", "habilidades directivas 2", 4, 5, "ingeniería en gestión empresarial"),
    ("emige4", "entorno macroeconómico", 4, 5, "ingeniería en gestión empresarial"),
    ("ioige4", "investigación de operaciones", 4, 5, "ingeniería en gestión empresarial"),
    ("foige5", "finanzas en las organizaciones", 5, 5, "ingeniería en gestión empresarial"),
    ("ei2ige5", "estadística inferencial 2", 5, 5, "ingeniería en gestión empresarial"),
    ("ipige5", "ingeniería de procesos", 5, 5, "ingeniería en gestión empresarial"),
    ("gchige5", "gestión del capital humano", 5, 5, "ingeniería en gestión empresarial"),
    ("ti1ige5", "taller de investigación 1", 5, 5, "ingeniería en gestión empresarial"),
    ("mige5", "mercadotecnia", 5, 5, "ingeniería en gestión empresarial"),
    ("assoige6", "administración de la salud y seguridad ocupacional", 6, 5, "ingeniería en gestión empresarial"),
    ("eeiige6", "el emprendedor y la innovación", 6, 5, "ingeniería en gestión empresarial"),
    ("gp1ige6", "gestión de la producción 1", 6, 5, "ingeniería en gestión empresarial"),
    ("doige6", "diseño organizacional", 6, 5, "ingeniería en gestión empresarial"),
    ("ti2ige6", "taller de investigación 2", 6, 5, "ingeniería en gestión empresarial"),
    ("simige6", "sistemas de información de mercadotecnia", 6, 5, "ingeniería en gestión empresarial"),
    ("cageige7", "calidad aplicada a la gestión empresarial", 7, 5, "ingeniería en gestión empresarial"),
    ("pnige7", "plan de negocios", 7, 5, "ingeniería en gestión empresarial"),
    ("gp2ige7", "gestión de la producción 2", 7, 5, "ingeniería en gestión empresarial"),
    ("geige7", "gestión estratégica", 7, 5, "ingeniería en gestión empresarial"),
    ("dsige7", "desarrollo sustentable", 7, 5, "ingeniería en gestión empresarial"),
    ("meige7", "mercadotecnia electrónica", 7, 5, "ingeniería en gestión empresarial"),
    ("trpige7", "taller de relaciones publicas", 7, 5, "ingeniería en gestión empresarial"),
    ("lteige8", "la tecnología y su entorno", 8, 5, "ingeniería en gestión empresarial"),
    ("dnpige8", "desarrollo de nuevos productos", 8, 5, "ingeniería en gestión empresarial"),
    ("csige8", "cadena de suministros", 8, 5, "ingeniería en gestión empresarial"),
    ("dmige8", "decisiones mercadológicas", 8, 5, "ingeniería en gestión empresarial"),
    ("tddige8", "taller de destrezas directivas", 8, 5, "ingeniería en gestión empresarial"),
    ("tlgfige8", "trámites legales y gestión del financiamiento", 8, 5, "ingeniería en gestión empresarial");
INSERT INTO tabla_materias(`clave`, `nombre`, `semestre`, `unidades`, `carrera`) VALUES
    ("fiii1", "fundamentos de investigación", 1, 5, "ingeniería industrial"),
    ("teii1", "taller de ética", 1, 5, "ingeniería industrial"),
    ("cdii1", "cálculo diferencial", 1, 5, "ingeniería industrial"),
    ("thiii1", "taller de herramientas intelectuales", 1, 5, "ingeniería industrial"),
    ("qii1", "química", 1, 5, "ingeniería industrial"),
    ("diii1", "dibujo industrial", 1, 5, "ingeniería industrial"),
    ("eeiii2", "electricidad y electrónica industrial", 2, 5, "ingeniería industrial"),
    ("pmii2", "propiedad de los materiales", 2, 5, "ingeniería industrial"),
    ("ciii2", "cálculo integral", 2, 5, "ingeniería industrial"),
    ("peii2", "probabilidad y estadística", 2, 5, "ingeniería industrial"),
    ("arnii2", "análisis de la realidad nacional", 2, 5, "ingeniería industrial"),
    ("tlii2", "taller de lirerazgo", 2, 5, "ingeniería industrial"),
    ("mnii3", "metrología y normalización", 3, 5, "ingeniería industrial"),
    ("alii3", "álgebra lineal", 3, 5, "ingeniería industrial"),
    ("cvii3", "cálculo vectorial", 3, 5, "ingeniería industrial"),
    ("eii3", "economía", 3, 5, "ingeniería industrial"),
    ("ei1ii3", "estadística inferencial 1", 3, 5, "ingeniería industrial"),
    ("et1ii3", "estudio del trabajo 1", 3, 5, "ingeniería industrial"),
    ("pfii4", "procesos de fabricación", 4, 5, "ingeniería industrial"),
    ("fii4", "física", 4, 5, "ingeniería industrial"),
    ("alpii4", "algoritmos y lenguajes de programación", 4, 5, "ingeniería industrial"),
    ("io1ii4", "investigación de operaciones 1", 4, 5, "ingeniería industrial"),
    ("ei2ii4", "estadística inferencial 2", 4, 5, "ingeniería industrial"),
    ("et2ii4", "estudio del trabajo 2", 4, 5, "ingeniería industrial"),
    ("hsiii4", "higiene y seguridad industrial", 4, 5, "ingeniería industrial"),
    ("apii5", "administración de proyectos", 5, 5, "ingeniería industrial"),
    ("gcii5", "gestión de costos", 5, 5, "ingeniería industrial"),
    ("ao1ii5", "administración de las operaciones 1", 5, 5, "ingeniería industrial"),
    ("io2ii5", "investigación de operaciones 2", 5, 5, "ingeniería industrial"),
    ("cecii5", "control estadístico de la calidad", 5, 5, "ingeniería industrial"),
    ("eii5", "ergonomía", 5, 5, "ingeniería industrial"),
    ("dsii5", "desarrollo sustentable", 5, 5, "ingeniería industrial"),
    ("ti1ii6", "taller de investigación 1", 6, 5, "ingeniería industrial"),
    ("ieii6", "ingeniería economíca", 6, 5, "ingeniería industrial"),
    ("ao2ii6", "administración de las operaciones 2", 6, 5, "ingeniería industrial"),
    ("sii6", "simulación", 6, 5, "ingeniería industrial"),
    ("amii6", "administración del matenimiento", 6, 5, "ingeniería industrial"),
    ("mii6", "mercadotécnia", 6, 5, "ingeniería industrial"),
    ("ti2ii7", "taller de investigación 2", 7, 5, "ingeniería industrial"),
    ("pfii7", "planeción financiera", 7, 5, "ingeniería industrial"),
    ("pdiii7", "planeación y diseño de instalaciones", 7, 5, "ingeniería industrial"),
    ("smii7", "sistemas de manofactura", 7, 5, "ingeniería industrial"),
    ("lcsii7", "logística y cadenas de suministro", 7, 5, "ingeniería industrial"),
    ("gscii7", "gestión de los sistemas de calidad", 7, 5, "ingeniería industrial"),
    ("isii7", "ingeniería de sistemas", 7, 5, "ingeniería industrial"),
    ("ipsii7", "ingeniería del producto y servicio", 7, 5, "ingeniería industrial"),
    ("fepii8", "formulación y evaluación de proyectos", 8, 5, "ingeniería industrial"),
    ("riii8", "relaciones industriales", 8, 5, "ingeniería industrial"),
    ("sicii8", "sistemas integrados para la calidad", 8, 5, "ingeniería industrial"),
    ("spii8", "simulación del proceso", 8, 5, "ingeniería industrial"),
    ("maii8", "manofactura automatizada", 8, 5, "ingeniería industrial"),
    ("tlii8", "tópicos lean", 8, 5, "ingeniería industrial"),
    ("opmii9", "optimización de procesos de manofactura", 9, 5, "ingeniería industrial"),
    ("dccii9", "diseño de la calidad y confiabilidad", 9, 5, "ingeniería industrial"),
    ("mmpii9", "medición y mejoramieno de la productividad", 9, 5, "ingeniería industrial");
INSERT INTO tabla_administradores(`clave`, `nombres`, `apellido_paterno`, `apellido_materno`, `fecha_nacimiento`, `sexo`, `email_institucional`, `contrasenia`, `foto_perfil`) VALUES
    ("21jmg201098", "guillermo", "jiménez", "montes", "1998-10-20", "masculino", "jmg201098@tecnm.mx", "12345678", "raw/img/usuario-defecto.jpg");